---
image:
  tag: v1.118.2

server:
  ingress:
    main:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - host: immich
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich

postgresql:
  enabled: true

redis:
  enabled: true

immich:
  persistence:
    library:
      existingClaim: immich-pvc
  metrics:
    enabled: true
  configuration:
    logging:
      enabled: true
      level: log
