---
immich:
  persistence:
    library:
      existingClaim: immich-pvc
  metrics:
    enabled: true

server:
  ingress:
    main:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - host: immich
          paths:
            - path: "/"
      tls:
        - hosts:
          - immich

postgresql:
  enabled: true

redis:
  enabled: true
